---
name: Release `jq` latest as WASM

on:
  workflow_call:
  workflow_dispatch:

jobs:
  job-a:
    runs-on: ubuntu-latest
    steps:
      - uses: Homebrew/actions/setup-homebrew@b50a1fd1a8d4df5cffc532716d4afb69a9c9d941 # SHA for commit at 2023-12-23

      - name: 'Install build requirement: `emscripten`'
        run: |
          brew install emscripten

      - name: 'Verify build requirement: `emscripten`'
        run: |
          emcc -v
