---
name: Release `jq` latest as WASM

on:
  workflow_call:
  workflow_dispatch:

jobs:
  job-a:
    runs-on: ubuntu-latest
    steps:
      - id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@b50a1fd1a8d4df5cffc532716d4afb69a9c9d941 # SHA for commit at 2023-12-23

      - id: cache-homebrew
        uses: actions/cache@v4
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: 'Install build requirement: `emscripten`'
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          brew install emscripten

      - name: 'Verify build requirement: `emscripten`'
        run: |
          emcc -v
