---
name: Release `jq` latest as WASM

on:
  workflow_call:
  workflow_dispatch:

jobs:
  job-a:
    runs-on: ubuntu-latest
    steps:
      - name: Install build requirement: `emscripten`
        run: |
          brew install emscripten

      - name: Verify build requirement: `emscripten`
        run: |
          ./emcc -v
