---
name: Release `jq` latest as WASM

on:
  workflow_call:
  workflow_dispatch:

jobs:
  job-a:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: Homebrew/actions/setup-homebrew@b50a1fd1a8d4df5cffc532716d4afb69a9c9d941 # SHA for commit at 2023-12-23

      - name: 'Install build requirement: `emscripten`'
        run: |
          brew install emscripten

      - name: 'Verify build requirement: `emscripten`'
        run: |
          emcc -v

      - name: 'Prep the `jq` module'
        run: |
          git submodule update --init
          autoreconf -i
          emconfigure ./configure --with-oniguruma=builtinrun
          emmake make -j8
          cp jq jq.o
        working-directory: jq

      - name: DEBUG
        run: |
          ls -AR jq

      - name: 'Try to do the thing with the `jq` module'
        run: |
          emcc -s EXPORTED_RUNTIME_METHODS='["callMain"]' -s ALLOW_MEMORY_GROWTH=1 -s EXPORT_NAME="jq" -s WASM=1 jq.o -o jq.wasm.js
        working-directory: jq
