---
name: Release `jq` latest as WASM

run-name: 'Release `jq` latest as WASM (from: ${{ github.ref }})'

on:
  workflow_call:
  workflow_dispatch:

jobs:
  job-a:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: Homebrew/actions/setup-homebrew@b50a1fd1a8d4df5cffc532716d4afb69a9c9d941 # SHA for commit at 2023-12-23

      - name: 'Install build requirement: `emscripten`'
        run: |
          brew install emscripten

      - name: 'Verify build requirement: `emscripten`'
        run: |
          emcc -v

      - name: 'Prep the `jq` module'
        run: |
          git submodule update --init
          autoreconf -i
          emconfigure ./configure --with-oniguruma=builtinrun
          emmake make LDFLAGS=-all-static
          cp jq jq.o
        working-directory: jq

      - name: 'Try to do the thing with the `jq` module'
        run: |
          emcc jq.o -o jq.js -s ERROR_ON_UNDEFINED_SYMBOLS=0
        working-directory: jq

      - name: Create test data
        id: test-data
        run: |
          tmpfile=$(mktemp)
          echo '{ "a": "b" }' > $tmpfile
          echo "json=$tmpfile" | tee -a $GITHUB_OUTPUT

      - env:
          JSON_FILE: ${{ steps.test-data.outputs.json }}
        run: |
          node jq/jq.js '.a' $JSON_FILE
